# Reshape
* The reshape function is used to shape the NumPy array

In [1]:
import numpy as np

In [2]:
example = np.arange(1,16)

In [3]:
example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [8]:
example.reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
example.reshape((3,1))

ValueError: cannot reshape array of size 15 into shape (3,1)

In [10]:
array = example.reshape((1,15))

In [11]:
array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [12]:
example.ndim

1

In [13]:
array.ndim

2

# max()
* the max() function is used to to return us the largest element in an array
# argmax()
* the argmax() function is used to  return the index of the largest element in an array

In [14]:
array = np.random.randint(0,15,10)

In [15]:
array

array([12,  9, 13,  9,  9,  2,  3,  8,  0,  1])

In [16]:
array.max()

13

In [17]:
array.argmax()

2

In [29]:
array2 = np.random.randint(0,60,(4,3))

In [30]:
array2

array([[16,  9, 39],
       [40,  0, 45],
       [16, 26,  2],
       [14, 27, 18]])

In [31]:
array2.max()

45

In [32]:
array2.argmax()

5

# min()
* the min() function is used to return the smallest element in an array
# argmin()
* the argmin() function is used to return the index of the smallest element in an array

In [33]:
array = np.random.randint(0,20,10)

In [34]:
array

array([ 5, 11, 15, 17, 13, 12,  3,  6, 13,  0])

In [35]:
array.min()

0

In [36]:
array.argmin()

9

In [37]:
array2 = np.random.randint(0,20,(5,3))

In [38]:
array2

array([[ 1,  3,  0],
       [10,  1, 18],
       [ 0,  8,  0],
       [12,  2,  2],
       [14, 15,  1]])

In [39]:
array2.min()

0

In [40]:
array2.argmin()

2

# Concatenation 

In [41]:
import numpy as np

In [47]:
array1= np.array([1,2,3,4])
array2= np.array([5,6,7,8])

In [48]:
np.concatenate([array1,array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
array3 = np.arange(1,7).reshape((2,3))

In [50]:
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
array4 = np.array([[7,8,9],[10,11,12]])

In [52]:
array4

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
np.concatenate([array3,array4])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
np.concatenate([array3,array4],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [65]:
np.concatenate([array1,array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [66]:
array5 = np.arange(1,11).reshape(5,2)

In [67]:
array5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [68]:
np.concatenate([array3,array5])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

# Splitting One Dimensional NumPy Array

In [69]:
import numpy as np

In [71]:
array =np.array([1,3,5,50,50,2,4,6])

In [83]:
array_split_1 = np.split(array,[3,5])

In [84]:
array_split_1

[array([1, 3, 5]), array([50, 50]), array([2, 4, 6])]

In [73]:
x, y, z =np.split(array,[3,5])

In [74]:
x

array([1, 3, 5])

In [75]:
y

array([50, 50])

In [76]:
z

array([2, 4, 6])

In [88]:
np.split(array,4)

[array([1, 3]), array([ 5, 50]), array([50,  2]), array([4, 6])]

In [91]:
np.split(array,5)

ValueError: array split does not result in an equal division

# Splitting Two Dimensional NumPy Array

In [92]:
import numpy as np

In [95]:
array_1 = np.arange(20).reshape(5,4)

In [96]:
array_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [104]:
np.split(array_1,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [105]:
x, y, z =np.split(array_1,[1,3])

In [106]:
x

array([[0, 1, 2, 3]])

In [107]:
y

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
z

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

# now we do this operation on column based not the row

In [109]:
np.split(array_1,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

# hsplit function

In [110]:
array_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [111]:
np.hsplit(array_1,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [112]:
np.hsplit(array_1,[1, 3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

# vsplit function

In [113]:
array_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [119]:
array_1.shape

(5, 4)

In [117]:
row, column =array_1.shape

In [120]:
np.vsplit(array_1,row)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [121]:
np.vsplit(array_1, [2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

# Sort

In [122]:
import numpy as np

In [123]:
variable = np.array([3,6,20,1,0,290,1])

In [124]:
variable

array([  3,   6,  20,   1,   0, 290,   1])

In [125]:
np.sort(variable)

array([  0,   1,   1,   3,   6,  20, 290])

In [126]:
variable

array([  3,   6,  20,   1,   0, 290,   1])

In [127]:
variable_2 = np.sort(variable)

In [128]:
variable_2

array([  0,   1,   1,   3,   6,  20, 290])

In [129]:
example = np.random.normal(30,10,(4,4))

In [130]:
example

array([[47.82346815, 29.49674043, 23.37170203, 42.03016658],
       [22.06643722, 42.72513087, 24.33592736, 27.16643609],
       [40.46263107, 31.06634556,  3.93073187, 30.89575919],
       [24.40275374, 45.69009236, 31.46629126, 21.54308857]])

In [131]:
np.sort(example,axis = 0) # based column

array([[22.06643722, 29.49674043,  3.93073187, 21.54308857],
       [24.40275374, 31.06634556, 23.37170203, 27.16643609],
       [40.46263107, 42.72513087, 24.33592736, 30.89575919],
       [47.82346815, 45.69009236, 31.46629126, 42.03016658]])

In [132]:
np.sort(example,axis = 1) # based row

array([[23.37170203, 29.49674043, 42.03016658, 47.82346815],
       [22.06643722, 24.33592736, 27.16643609, 42.72513087],
       [ 3.93073187, 30.89575919, 31.06634556, 40.46263107],
       [21.54308857, 24.40275374, 31.46629126, 45.69009236]])