# Indexing

In [1]:
import numpy as np

In [2]:
array = np.arange(0,11)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array[4]

4

In [6]:
array[-1]

10

In [19]:
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
array_2[0][0]

1

In [26]:
array_2[0, 0]

1

In [25]:
array_2[0:, 0]

array([1, 4, 7])

In [27]:
array_2[2, 1]

8

In [34]:
array_2[-1, -3]

array_2[-1, 0]

7

# Slicing One-Dimensional array

In [3]:
import numpy as np

In [4]:
example = np.arange(10,20)

In [5]:
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Syntax
* [start,stop,step]

In [6]:
example[2:5]

array([12, 13, 14])

In [7]:
example[3::2]

array([13, 15, 17, 19])

In [8]:
example[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

# Slicing Two-Dimensional Array

In [9]:
import numpy as np

In [12]:
array = np.arange(30).reshape(6,5)

In [13]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [16]:
array[2,:]

array([10, 11, 12, 13, 14])

In [15]:
array[2,::2]

array([10, 12, 14])

In [17]:
array[0]

array([0, 1, 2, 3, 4])

In [18]:
array[:,3]

array([ 3,  8, 13, 18, 23, 28])

In [20]:
array[:, 0]

array([ 0,  5, 10, 15, 20, 25])

In [21]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [24]:
array[1:4,:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [25]:
array[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

# Assign values to one Dimensional array

In [26]:
import numpy as np

In [27]:
variable = np.array([0,1,2,3,4,5,6,7,8,9])

In [28]:
variable[4] = 99

In [29]:
variable

array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9])

In [30]:
variable[0:5]=[2,4,6,8,10]

In [31]:
variable

array([ 2,  4,  6,  8, 10,  5,  6,  7,  8,  9])

In [32]:
variable[5:]

array([5, 6, 7, 8, 9])

In [33]:
variable[0:5]=10

In [34]:
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [35]:
variable[0:5]=20,30,40,50,60

In [36]:
variable

array([20, 30, 40, 50, 60,  5,  6,  7,  8,  9])

# Assigning Value Two-Dimensional Array

In [38]:
import numpy as np

In [44]:
example = np.array([[10,20,30],
                    [40,50,60],
                    [70,80,90]])

In [45]:
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [48]:
example[1,1]=100

In [51]:
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [52]:
type(example)

numpy.ndarray

In [53]:
example[1,0]=100.6

In [54]:
example

array([[ 10,  20,  30],
       [100, 100,  60],
       [ 70,  80,  90]])

In [55]:
example[:,2]=100

In [56]:
example

array([[ 10,  20, 100],
       [100, 100, 100],
       [ 70,  80, 100]])

In [57]:
example[0::2,0:2]

array([[10, 20],
       [70, 80]])

In [58]:
example[0::2,0:2] = [99,89],[100,20]

In [59]:
example

array([[ 99,  89, 100],
       [100, 100, 100],
       [100,  20, 100]])

# Fancy Indexing of One-Dimensional Array

In [60]:
import numpy as np

In [61]:
fancy = np.arange(0,50,5)

In [62]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [63]:
fancy[1]

5

In [64]:
fancy[3]

15

In [65]:
fancy[5]

25

In [66]:
[fancy[1],fancy[2],fancy[3]]

[5, 10, 15]

In [67]:
indexes =[1,3,5]

In [70]:
fancy[indexes]

array([ 5, 15, 25])

In [71]:
array = np.array([1,3,5])

In [72]:
fancy[array]

array([ 5, 15, 25])

# Fancy Indexing Two-Dimensional Array

In [73]:
import numpy as np

In [74]:
variable = np.zeros((10,10),dtype="int")

In [75]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [76]:
variable.shape

(10, 10)

In [77]:
row = variable.shape[0]

In [78]:
for i in range(row):
    variable[i] = i

In [79]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [80]:
list1 =[1,3,5,7]

In [81]:
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [83]:
list2 = [8,5,2,7,3]

In [84]:
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [85]:
example = np.arange(1,17).reshape((4,4))

In [86]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

example[[row index ,...] , [column index ,...]]

In [87]:
example[[0,3],[1,2]]

array([ 2, 15])

In [88]:
row = [0,2,3,1]
column = [3,0,2,1]

In [89]:
example[row,column]

array([ 4,  9, 15,  6])

# Combining Fancy Index with Normal Indexing

In [90]:
import numpy as np

In [91]:
example = np.arange(1,17).reshape((4,4))

In [92]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
example[1,[1,3]]

array([6, 8])

In [95]:
example[[0,3],1]

array([ 2, 14])

# Combining Fancy Index with Normal Slicing

In [96]:
import numpy as np

In [97]:
example = np.arange(1,17).reshape((4,4))

In [98]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [99]:
example[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [100]:
example[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [103]:
example[2:0:-1,[1,2]]

array([[10, 11],
       [ 6,  7]])