# Array
it's a data structure in the NumPy Library. You can think of it as a List , Dictionary , or Tuple

In [1]:
import numpy as np

In [2]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [3]:
variable =[5.8,9,7,5]

In [4]:
for i in range(len(variable)):
    print(type(variable[i]))

<class 'float'>
<class 'int'>
<class 'int'>
<class 'int'>


In [5]:
new_variable = np.array([5.8,9,7,5])

In [7]:
new_variable

array([5.8, 9. , 7. , 5. ])

In [6]:
for i in range(len(new_variable)):
    print(type(new_variable[i]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [8]:
new_variable2 = np.array([5.8,9,7,5], dtype="int")

In [9]:
new_variable2

array([5, 9, 7, 5])

# Zeros
* This functions produces an array of zeros of whatever the size we want. In other words, the array we create will consist of all zeros.
* The data type that we will write inside the zeros functions is a tuple
* The tuple value is the size of the array that we want to create.

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones((3,4,5), dtype="int")

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

# Full
* With this function, we're going to fill the arrays of the size and shape that we want with the number that we want

In [30]:
import numpy as np

In [32]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [33]:
np.full((2,3), 6, dtype="float")

array([[6., 6., 6.],
       [6., 6., 6.]])

# Arange

* This function will create an array of numbers from the start to the end (exclusive).
* The step size is the difference between each number in the array.
    * arange (start,stop,step,dtype)


In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
example = np.arange(3,10,dtype="float")

In [38]:
print(example)

[3. 4. 5. 6. 7. 8. 9.]


In [39]:
type(example)

numpy.ndarray

# Eye

* This function creates an identity matrix.
* An identity matrix is a square matrix in which all the elements of the principal diagonal are ones, and all other elements are zeros.
* The size of the array that we create is a tuple.
* The dtype value is the data type that we want to write inside the array.

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
np.eye(3,2,dtype="bool")

array([[ True, False],
       [False,  True],
       [False, False]])

# LINESPACE

* This function creates an array of numbers that are evenly spaced within a given range.
* The size of the array that we create is a tuple.
* The dtype value is the data type that we want to write inside the array.

In [46]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [47]:
np.random.rand(5)

array([0.80480342, 0.13460371, 0.7600208 , 0.22997261, 0.04111127])

In [48]:
np.random.rand(2,3)

array([[0.25651655, 0.46776938, 0.59270355],
       [0.41212191, 0.09648687, 0.67780309]])

In [49]:
np.random.randn(5)

array([-1.20726598, -0.50462367,  1.21508053,  0.17822475,  0.09362559])

In [50]:
np.random.normal(20,5,(4,3))

array([[21.19859186, 18.61141903, 13.88057076],
       [11.16562679, 14.75219886, 16.4690633 ],
       [22.03284742, 19.43655696, 23.75648393],
       [32.78179742, 23.44937488, 16.43752494]])

In [51]:
np.random.randint(0,10,(3,4))

array([[1, 5, 6, 1],
       [7, 5, 1, 9],
       [6, 3, 7, 6]])

# Properties of NumPy Array 
* ndim 
    * it's gives us information about the number of dimensions of the array
* shape 
    * it gives us information about the size of the array in terms of the number of elements
* size 
    * it gives us information about the total number of elements in the array
* dtype
    * it gives us information about the data type of the elements in the array

In [52]:
matrix = np.random.randint(0,10,(3,3))

In [53]:
matrix

array([[4, 6, 3],
       [8, 4, 4],
       [7, 5, 1]])

In [54]:
matrix.ndim

2

In [55]:
matrix.shape

(3, 3)

In [56]:
matrix.size

9

In [57]:
matrix.dtype

dtype('int32')