# Operations with Comparison operators

In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)

In [3]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [6]:
condition = array <=4

In [8]:
condition

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [7]:
array[condition]

array([1, 2, 3, 4])

In [9]:
new_condition = (array !=8) & (array >=6)

In [10]:
array[new_condition]

array([ 6,  7,  9, 10])

In [11]:
new_condition_2 = (array !=8) | (array >=6)

In [12]:
array[new_condition_2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Arithmetic operations in Numpy
# ufunc
* Subtraction, Multiplication, Division, Exponentiation, Modulus, Floor Division, Addition, and Logarithmic Operations in Numpy

In [13]:
import numpy as np

In [14]:
array = np.arange(1,11)

In [15]:
array -2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [18]:
array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [19]:
array /10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
((array *10) +20) /5

array([ 6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.])

In [21]:
array * array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [22]:
array / array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.subtract(array,2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [25]:
np.multiply(array,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [26]:
np.add(array,20)

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [27]:
np.divide(array,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [28]:
array **3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [29]:
np.power(array,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [31]:
np.sqrt(4)

2.0

In [32]:
np.sqrt(100)

10.0

In [33]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [34]:
np.mod(array, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [35]:
np.sin(180)

-0.8011526357338304

In [36]:
np.cos(180)

-0.5984600690578581

In [38]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [39]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [37]:
np.cos(array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

# Statistical Operations in NumPy

In [40]:
import numpy as np

In [41]:
array = np.arange(1,11)

In [42]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.sum(array)

55

In [44]:
np.mean(array)

5.5

In [45]:
np.median(array)

5.5

In [46]:
np.min(array)

1

In [47]:
np.max(array)

10

In [48]:
np.std(array)

2.8722813232690143

In [49]:
np.var(array)

8.25

In [50]:
np.sqrt(np.var(array))

2.8722813232690143

# Solving Second-Degree Equations with NumPy


In [51]:
import numpy as np

2X1 + X2= 5  

-3X1 + 6X2 =0


In [52]:
coefficient = np.array([[2, 1], [-3, 6]])

In [53]:
coefficient

array([[ 2,  1],
       [-3,  6]])

In [54]:
output = np.array([5, 0])

In [55]:
output

array([5, 0])

In [56]:
np.linalg.solve(coefficient, output)

array([2., 1.])